import { Inter } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "./components/MyContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContextProvider>
          {children}
          <Toaster />
        </MyContextProvider>
      </body>
    </html>
  );
}
